spring:
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/standard_dev
#    url: jdbc:mariadb://localhost:3306/standard_dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.mariadb.jdbc.Driver
